#!/usr/bin/with-contenv bash

# permissions
chown abc:abc \
/dataWebDAV
chmod 777 /dataWebDAV

# set webdav config
[[ ! -f /config/nginx/site-confs/webdav ]] && \
cp /defaults/webdav /config/nginx/site-confs/
