#!/usr/bin/with-contenv bash

# permissions
chown abc:abc \
/data_webdav
chmod 777 /data_webdav

# set webdav config
if [ ! -f /config/nginx/site-confs/webdav ]; then
cp /defaults/webdav /config/nginx/site-confs/webdav
fi
