#!/usr/bin/with-contenv bash

# permissions
chown abc:abc \
/dataWebDAV
chmod 777 /dataWebDAV

# set webdav config
if [ ! -f /config/nginx/site-confs/webdav ]; then
cp /defaults/webdav /config/nginx/site-confs/webdav
fi
