#!/usr/bin/with-contenv bash

# 优先判断是否是 -v 多用户模式
#if [ -e /etc/nginx/htpasswd ]; then exit 0; fi

# 再判断是否是 -e 单用户模式
if [ -n "$USERNAME" ]
then
htpasswd -bc /etc/nginx/htpasswd $USERNAME $PASSWORD
echo "Add User Success"
# exit 0
fi

# 两种用户模式都没有设置，则报错提示
#echo "Error ,错误！检查是否正确配置用户！"
#exit 1
